export const today = [
	{
		name: "HAVIT HV-G92 Gamepad",
		price: 120,
		oldPrice: 160,
		img: "/assets/images/products/joystick.png",
		rating: 4.5,
		reviews: 88,
	},
	{
		name: "AK-900 Wired Keyboard",
		price: 960,
		oldPrice: 1160,
		img: "/assets/images/products/keyboard.png",
		rating: 4,
		reviews: 75,
	},
	{
		name: "LCD Monitor",
		price: 370,
		oldPrice: 400,
		img: "/assets/images/products/monitor.png",
		rating: 5,
		reviews: 99,
	},
	{
		name: "S-Series Comfort Chair ",
		price: 375,
		oldPrice: 400,
		img: "/assets/images/products/chair.png",
		rating: 4.5,
		reviews: 99,
	},
	{
		name: "ASUS FHD Gaming Laptop",
		price: 700,
		oldPrice: 990,
		img: "/assets/images/products/laptop.png",
		rating: 5,
		reviews: 325,
	},
	{
		name: "Jr. Zoom Soccer Cleats",
		price: 880,
		oldPrice: 1160,
		img: "/assets/images/products/copa.png",
		rating: 5,
		reviews: 35,
	},
];
export const month = [
	{
		name: "The North Coat",
		price: 260,
		oldPrice: 360,
		img: "/assets/images/products/joystick.png",
		rating: 5,
		reviews: 66,
	},
	{
		name: "Gucci Duffle Bag",
		price: 960,
		oldPrice: 1160,
		img: "/assets/images/products/keyboard.png",
		rating: 4.5,
		reviews: 65,
	},
	{
		name: "Another Gamepad",
		price: 160,
		oldPrice: 170,
		img: "/assets/images/products/monitor.png",
		rating: 4.5,
		reviews: 57,
	},
	{
		name: "S-Series Comfort Chair ",
		price: 360,
		oldPrice: 460,
		img: "/assets/images/products/chair.png",
		rating: 5,
		reviews: 65,
	},
	{
		name: "GP11 Shooter USB Gamepad",
		price: 660,
		oldPrice: 990,
		img: "/assets/images/products/laptop.png",
		rating: 5,
		reviews: 104,
	},
	{
		name: "Kids Electric Car",
		price: 580,
		oldPrice: 680,
		img: "/assets/images/products/copa.png",
		rating: 5,
		reviews: 84,
	},
];

